#!/usr/bin/env bash

#### Retrieve Singularity image if necessary

img='r-4.0'
id='77DD71E598E5B51B'
auth='AJdCAAZQQrCo9cc'
if [ ! -f src/${img}.sif ]; then
    wget -O src/${img}.sif \
        "https://onedrive.live.com/download?cid=${id}&resid=${id}%2124983&authkey=${auth}"
fi
# building the singularity image was done by executing the command:
# singularity build --remote src/${img}.sif src/${img}.singularity
# (after authorizing singularity remote builder)

#### Define R parameters
pro_input='input/spe_Report_Proteins.csv' #the csv file of the protein groups quntification generated by SN
#pep_input='' #the csv file of the peptide intensity from the SN
project_name='test' #the name of this project
outdir='./output' #output dir
design_matrix='input/design_matrix.csv' #csv file of design matrix for comparison
#normalization='' # 'T' or 'F'

r_script='processing.R'

module load singularity

singularity run -H $PWD:/home src/${img}.sif \
    Rscript src/${r_script} \
    --pro_input ${pro_input} \
    -p ${project_name} \
    -o ${outdir} \
    --design_matrix ${design_matrix}
