#!/usr/bin/env bash

#### Retrieve Singularity image if necessary

img='r-4.0'
if [ ! -f src/${img}.sif ]; then
    singularity pull src/${img}.sif \
        library://wellerca/remote-builds/rb-63c96b25db466da3722a5a6c:latest
fi

desiredsum='854e2cbeb45d731d7e89f6226c9a8f97b0658313'
actualsum=$(shasum src/${img}.sif | awk '{print $1}')

if [ "${desiredsum}" != "${actualsum}" ]; then
    echo "src/${img}.sif  checksum failed! removing src/${img}.sif ... try again!"
    rm src/${img}.sif
    exit 1
fi

# building the singularity image was done by executing the command:
# singularity build --remote src/${img}.sif src/${img}.singularity
# (after authorizing singularity remote builder)

#### Define R parameters
pro_input='input/spe_Report_Proteins.csv' #the csv file of the protein groups quntification generated by SN
#pep_input='' #the csv file of the peptide intensity from the SN
project_name='test' #the name of this project
outdir='./output' #output dir
design_matrix='input/design_matrix.csv' #csv file of design matrix for comparison
#normalization='' # 'T' or 'F'

r_script='processing.R'

module load singularity

singularity run -H $PWD:/home src/${img}.sif \
    Rscript src/${r_script} \
    --pro_input ${pro_input} \
    -p ${project_name} \
    -o ${outdir} \
    --design_matrix ${design_matrix}
